name: laboral_app
description: Employee time tracker app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1

flutter:

  uses-material-design: true

  assets:
    - lib/assets/

    # Localization
    - lib/localization/en.json
    - lib/localization/ru.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Regular.ttf


